---
- name: Set Up VM for Homelab
  hosts: vm
  gather_facts: true
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

  tasks:
    - include_role: 
        name: base_packages
      tags: base_packages


    




