# Base Packages for Homelab

base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git
  - ufw
  - python3-pip
  - python3-venv
  - python3-dev
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-setuptools
  - python3-wheel
  - python3-cffi
  - python3-cryptography
  - python3-yaml
  - python3-jinja2
  - python3-apt
  - python3-pycurl
  - python3-requests
  - python3-urllib3
  - python3-six
  - python3-httplib2
  - python3-netaddr
  - python3-netifaces
  - python3-paramiko
  - tmux
  - vim
  - wget
  - unzip
  - jq
  - htop
  - nmap
  - dnsutils
  - net-tools
  - iputils-ping
  - iproute2
  - iperf3
  - fuse
  - rclone
  - rsync
  - sshpass
  - tree
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh-theme-powerlevel9k
  - fonts-powerline
  - neofetch
  - ansible-core
  

k8s_packages:
  - kubelet
  - kubeadm
  - kubectl


docker_packages:
  - docker-ce-cli
  - docker-ce
  - containerd.io
  - docker-compose